In [2]:
import tensorflow as tf
from tensorflow.contrib.losses.python.metric_learning.metric_loss_ops import pairwise_distance

In [8]:
data_size = 32
input_dim = 3
output_dim = 2
num_class = 4
x = tf.random.normal((data_size,input_dim))
y_ = 8*list(range(num_class))
targets = tf.convert_to_tensor(y_)

In [12]:
x.eval(session=tf.Session())

array([[-1.1270827 , -0.725593  , -0.34690222],
       [ 0.28178513,  0.45674577,  2.0411606 ],
       [ 1.2154179 ,  0.14189994, -2.670026  ],
       [ 0.70642304, -0.00769803, -0.8474639 ],
       [ 0.89888465, -0.13177611, -1.2516416 ],
       [-1.2670491 , -0.5573973 , -0.11814583],
       [-0.9562287 , -0.3078877 , -2.2464993 ],
       [ 0.6981849 , -0.15564477,  0.9964945 ],
       [-0.5819442 ,  0.6383627 ,  0.15348384],
       [ 0.80205494, -0.4372235 ,  0.21274656],
       [-0.45393866, -0.9244106 , -1.3156794 ],
       [ 0.10284877,  1.1832486 ,  0.05495634],
       [ 1.263614  ,  0.95658267,  0.70701236],
       [-0.16087732,  1.012355  ,  0.31901708],
       [ 0.73518056, -0.8514376 , -1.1671789 ],
       [-1.7243102 , -1.6181935 , -0.33250546],
       [ 1.0470356 , -0.28304663, -0.41981512],
       [ 0.01854724, -0.0299547 , -0.47024885],
       [-0.8447945 , -1.0083635 ,  0.20486952],
       [-1.0159105 ,  1.9276029 ,  1.3247596 ],
       [ 0.34921476, -1.2117742 ,  0.536

In [21]:
import numpy as np
inputs=np.load('inputs.npy')
tf.convert_to_tensor(inputs,np.float32).eval(session=tf.Session())

array([[0.3324203 , 0.68558335, 0.15228677],
       [0.75287515, 0.7687714 , 0.6182537 ],
       [0.27421302, 0.21996629, 0.9692856 ],
       [0.4817635 , 0.5265419 , 0.8199338 ],
       [0.95669675, 0.6536439 , 0.7072519 ],
       [0.13427421, 0.05725547, 0.32009283],
       [0.5711257 , 0.7083844 , 0.49613234],
       [0.15552741, 0.7137213 , 0.92263484],
       [0.8203503 , 0.13003069, 0.81271714],
       [0.9780575 , 0.24323066, 0.83346343],
       [0.5220975 , 0.4623779 , 0.9860648 ],
       [0.4375606 , 0.855193  , 0.64840853],
       [0.89222306, 0.06566145, 0.11655815],
       [0.7064045 , 0.5948679 , 0.12268396],
       [0.04687909, 0.9482258 , 0.67971927],
       [0.15982309, 0.9734723 , 0.6525185 ],
       [0.32872286, 0.8011196 , 0.23515566],
       [0.76239556, 0.4998424 , 0.22418725],
       [0.81363416, 0.8485694 , 0.2725195 ],
       [0.22374408, 0.8923387 , 0.68313473],
       [0.57579464, 0.48649254, 0.08187796],
       [0.77164483, 0.80077696, 0.06365427],
       [0.

In [16]:
np.load('targets.npy')

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [29]:
inputs=tf.convert_to_tensor(inputs)
inputs=tf.one_hot(inputs,depth=4)

TypeError: Value passed to parameter 'indices' has DataType float64 not in list of allowed values: uint8, int32, int64

In [30]:
targets=np.load('targets.npy')
targets=tf.convert_to_tensor(targets)
targets=tf.one_hot(targets,depth=4)

In [32]:
targets.eval(session=tf.Session()).shape

(32, 4)

In [35]:
inputs=np.load('inputs.npy')
embeddings=tf.convert_to_tensor(inputs,np.float32)
targets=np.load('targets.npy')
targets=tf.convert_to_tensor(targets)
labels=tf.one_hot(targets,depth=4)

In [37]:
num_of_instances_per_appeared_class=tf.expand_dims(tf.cast(tf.reduce_sum(labels,axis=0),tf.float32)+1e-6,axis=1)
num_of_instances_per_appeared_class.eval(session=tf.Session())

array([[8.000001],
       [8.000001],
       [8.000001],
       [8.000001]], dtype=float32)

In [47]:
A=tf.cast(tf.reduce_sum(labels,axis=0),tf.float32)
A(tf.equal(A,0)).eval(session=tf.Session())

TypeError: 'Tensor' object is not callable

In [59]:
tf.where(tf.equal(A,0),A,tf.Constant(1e-6).eval(session=tf.Session())

SyntaxError: unexpected EOF while parsing (<ipython-input-59-e5bbe3e21d64>, line 1)

In [57]:
tf.equal(A,0).eval(session=tf.Session())

array([False, False, False, False])

In [64]:
margin=1
num_of_instances_per_appeared_class=tf.reduce_sum(labels,axis=0)
num_of_instances_per_appeared_class=tf.where(tf.not_equal(num_of_instances_per_appeared_class,0),num_of_instances_per_appeared_class,tf.ones(num_of_instances_per_appeared_class.shape)*1e-6)
num_of_instances_per_appeared_class=tf.expand_dims(tf.reduce_sum(labels,axis=0),axis=1)
appeared_labels=tf.cast(labels,tf.float32)
sum_of_embeddings_per_appeared_class=tf.transpose(tf.matmul(tf.transpose(embeddings),appeared_labels))#num_of_appeared_class*num_feature
mean_embedding_per_appeared_class=sum_of_embeddings_per_appeared_class/num_of_instances_per_appeared_class

square_diff_per_instance=tf.square(embeddings-tf.gather(mean_embedding_per_appeared_class,tf.argmax(appeared_labels,axis=1)))
sum_of_square_diff_per_appeared_class=tf.reduce_sum(tf.transpose(tf.matmul(tf.transpose(square_diff_per_instance),appeared_labels)),axis=1)
sum_of_square_diff_per_appeared_class=tf.expand_dims(sum_of_square_diff_per_appeared_class,axis=1)
var_of_embeddings_per_appeared_class=sum_of_square_diff_per_appeared_class/num_of_instances_per_appeared_class

inter_loss_matrix=pairwise_distance(mean_embedding_per_appeared_class, squared=True)
intra_loss_matrix=var_of_embeddings_per_appeared_class+tf.transpose(var_of_embeddings_per_appeared_class)

loss_matrix=tf.maximum(intra_loss_matrix-inter_loss_matrix+margin,0)
loss_matrix=loss_matrix-loss_matrix*tf.diag(tf.ones([tf.shape(loss_matrix)[0]]))

fisher_loss=tf.reduce_max(loss_matrix)

In [87]:
tf.maximum(intra_loss_matrix-inter_loss_matrix+margin,0).eval(session=tf.Session())

array([[1.5680118, 1.4967222, 1.223318 , 1.2863318],
       [1.4967222, 1.4479961, 1.219458 , 1.2751089],
       [1.223318 , 1.219458 , 1.2980132, 1.3224764],
       [1.2863318, 1.2751089, 1.3224764, 1.3511205]], dtype=float32)

In [88]:
loss_matrix.eval(session=tf.Session())

array([[0.       , 1.4967222, 1.223318 , 1.2863318],
       [1.4967222, 0.       , 1.219458 , 1.2751089],
       [1.223318 , 1.219458 , 0.       , 1.3224764],
       [1.2863318, 1.2751089, 1.3224764, 0.       ]], dtype=float32)

In [73]:
tf.argmax(appeared_labels,axis=1).eval(session=tf.Session())

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64)

In [76]:
tf.gather(mean_embedding_per_appeared_class,tf.argmax(appeared_labels,axis=1)).shape

TensorShape([Dimension(32), Dimension(3)])