In [4]:
import torch
from torch.autograd import Variable

In [6]:
data_size = 32
input_dim = 3
output_dim = 2
num_class = 4
x = Variable(torch.rand(data_size, input_dim), requires_grad=False)
w = Variable(torch.rand(input_dim, output_dim), requires_grad=True)
inputs = x.mm(w)
y_ = 8*list(range(num_class))
targets = Variable(torch.IntTensor(y_))

In [12]:
import numpy as np

In [17]:
inputs=np.random.rand(data_size,input_dim)

In [20]:
targets=np.array(8*list(range(num_class)))

In [24]:
np.save('inputs.npy',inputs)
np.save('targets.npy',targets)

In [33]:
torch.from_numpy(inputs)

tensor([[0.3324, 0.6856, 0.1523],
        [0.7529, 0.7688, 0.6183],
        [0.2742, 0.2200, 0.9693],
        [0.4818, 0.5265, 0.8199],
        [0.9567, 0.6536, 0.7073],
        [0.1343, 0.0573, 0.3201],
        [0.5711, 0.7084, 0.4961],
        [0.1555, 0.7137, 0.9226],
        [0.8204, 0.1300, 0.8127],
        [0.9781, 0.2432, 0.8335],
        [0.5221, 0.4624, 0.9861],
        [0.4376, 0.8552, 0.6484],
        [0.8922, 0.0657, 0.1166],
        [0.7064, 0.5949, 0.1227],
        [0.0469, 0.9482, 0.6797],
        [0.1598, 0.9735, 0.6525],
        [0.3287, 0.8011, 0.2352],
        [0.7624, 0.4998, 0.2242],
        [0.8136, 0.8486, 0.2725],
        [0.2237, 0.8923, 0.6831],
        [0.5758, 0.4865, 0.0819],
        [0.7716, 0.8008, 0.0637],
        [0.4058, 0.8306, 0.7508],
        [0.5420, 0.4746, 0.9838],
        [0.7328, 0.3135, 0.9274],
        [0.6032, 0.6289, 0.3127],
        [0.2992, 0.6876, 0.5736],
        [0.4998, 0.7625, 0.1210],
        [0.0325, 0.0674, 0.0866],
        [0.095

In [57]:
targets=torch.zeros(targets.shape[0], targets.max()+1).scatter_(1,torch.unsqueeze(targets.long(),1), 1)

In [252]:
targets=torch.from_numpy(np.load('targets.npy'))

In [66]:
num_of_instances_per_appeared_class=torch.unsqueeze(targets.sum(0),1)

In [82]:
num_of_instances_per_appeared_class=targets.sum(0)

In [86]:
num_of_instances_per_appeared_class[num_of_instances_per_appeared_class!=0]+=1e-6

tensor([8.0000, 8.0000, 8.0000, 8.0000])

In [99]:
A=torch.rand(3,2)

 A==0

In [111]:
targets

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [113]:
targets=torch.zeros(targets.shape[0], targets.max()+1).scatter_(1,torch.unsqueeze(targets.long(),1), 1)#转成one_hot编码
num_of_instances_per_appeared_class=torch.unsqueeze(targets.sum(0),1)
num_of_instances_per_appeared_class[num_of_instances_per_appeared_class==0]=1e-6#避免除零操作


In [114]:
num_of_instances_per_appeared_class

tensor([[8.],
        [8.],
        [8.],
        [8.]])

In [135]:
transposedTargets=targets.t()

In [138]:
sum_of_embeddings_per_appeared_class=transposedTargets.mm(inputs.float())

In [145]:
mean_embedding_per_appeared_class=sum_of_embeddings_per_appeared_class/num_of_instances_per_appeared_class

In [164]:
square_diff_per_instance=(inputs.float()-torch.index_select(input=mean_embedding_per_appeared_class,dim=0,index=targets.long()))**2

In [167]:
sum_of_square_diff_per_appeared_class=torch.mm(transposedTargets,square_diff_per_instance).sum(1)

In [170]:
sum_of_square_diff_per_appeared_class=torch.unsqueeze(sum_of_square_diff_per_appeared_class,1)

In [174]:
var_of_embeddings_per_appeared_class

tensor([[0.2840],
        [0.2240],
        [0.1490],
        [0.1756]])

In [172]:
var_of_embeddings_per_appeared_class=sum_of_square_diff_per_appeared_class/num_of_instances_per_appeared_class

In [175]:
from torch.nn.functional import pairwise_distance

In [178]:
pairwise_distance(mean_embedding_per_appeared_class,mean_embedding_per_appeared_class,p=2)

tensor([1.7321e-06, 1.7321e-06, 1.7321e-06, 1.7321e-06])

In [179]:
def expanded_pairwise_distances(x, y=None):
    '''
    Input: x is a Nxd matrix
           y is an optional Mxd matirx
    Output: dist is a NxM matrix where dist[i,j] is the square norm between x[i,:] and y[j,:]
            if y is not given then use 'y=x'.
    i.e. dist[i,j] = ||x[i,:]-y[j,:]||^2
    '''
    if y is not None:
         differences = x.unsqueeze(1) - y.unsqueeze(0)
    else:
        differences = x.unsqueeze(1) - x.unsqueeze(0)
    distances = torch.sum(differences * differences, -1)
    return distances

In [183]:
inter_loss_matrix=expanded_pairwise_distances(mean_embedding_per_appeared_class)
intra_loss_matrix=var_of_embeddings_per_appeared_class+var_of_embeddings_per_appeared_class.t()

In [225]:
inter_loss_matrix

tensor([[0.0000, 0.0113, 0.2097, 0.1732],
        [0.0113, 0.0000, 0.1535, 0.1244],
        [0.2097, 0.1535, 0.0000, 0.0021],
        [0.1732, 0.1244, 0.0021, 0.0000]])

In [226]:
inter_loss_matrix.max(0)

(tensor([0.2097, 0.1535, 0.2097, 0.1732]), tensor([2, 2, 0, 0]))

In [187]:
torch.max(intra_loss_matrix-inter_loss_matrix+1,0)

(tensor([1.5680, 1.4967, 1.3225, 1.3511]), tensor([0, 0, 3, 3]))

In [227]:
inter_loss,_=inter_loss_matrix.max(0)
intra_loss=var_of_embeddings_per_appeared_class

In [228]:
intra_loss

tensor([[0.2840],
        [0.2240],
        [0.1490],
        [0.1756]])

In [196]:
loss_matrix=intra_loss_matrix-inter_loss_matrix+1
loss_matrix[loss_matrix<0]=0

In [201]:
loss_matrix=loss_matrix-torch.eye(loss_matrix.shape[0])*loss_matrix

In [205]:
torch.log(loss_matrix)

tensor([[  -inf, 0.4033, 0.2016, 0.2518],
        [0.4033,   -inf, 0.1984, 0.2430],
        [0.2016, 0.1984,   -inf, 0.2795],
        [0.2518, 0.2430, 0.2795,   -inf]])

In [206]:
def euclidean_dist(inputs_):
    # Compute pairwise distance, replace by the official when merged
    n = inputs_.size(0)
    dist = torch.pow(inputs_, 2).sum(dim=1, keepdim=True).expand(n, n)
    dist = dist + dist.t()
    dist.addmm_(1, -2, inputs_, inputs_.t())
    dist = dist.clamp(min=1e-12).sqrt()  # for numerical stability
    return dist

In [208]:
 euclidean_dist(inputs).shape

torch.Size([32, 32])

In [210]:
data_size = 32
input_dim = 3
output_dim = 2
num_class = 3
an_margin = 0.7
ap_margin = 0.3
x = Variable(torch.rand(data_size, input_dim), requires_grad=False)
w = Variable(torch.rand(input_dim, output_dim), requires_grad=True)
print('training data is ', x)
print('initial parameters are ', w)
inputs = x.mm(w)
print('extracted feature is :', inputs)
y_ = np.random.randint(num_class, size=data_size)
targets = Variable(torch.from_numpy(y_))

training data is  tensor([[0.7918, 0.8124, 0.4573],
        [0.6980, 0.1915, 0.4943],
        [0.0552, 0.7625, 0.6164],
        [0.3715, 0.2368, 0.8934],
        [0.4227, 0.3490, 0.9166],
        [0.4253, 0.4417, 0.1607],
        [0.0072, 0.8039, 0.9495],
        [0.1067, 0.6162, 0.5311],
        [0.8616, 0.6075, 0.4199],
        [0.4528, 0.7117, 0.4139],
        [0.2457, 0.8873, 0.3406],
        [0.7230, 0.8553, 0.6650],
        [0.9767, 0.0203, 0.0876],
        [0.0785, 0.4098, 0.7339],
        [0.6217, 0.1393, 0.5839],
        [0.7409, 0.0082, 0.8689],
        [0.8467, 0.2072, 0.4078],
        [0.4747, 0.2405, 0.6764],
        [0.5084, 0.2390, 0.8339],
        [0.7019, 0.2145, 0.9423],
        [0.3267, 0.9125, 0.8815],
        [0.2173, 0.4135, 0.7762],
        [0.7723, 0.8599, 0.7857],
        [0.0903, 0.7007, 0.0624],
        [0.6417, 0.0987, 0.2302],
        [0.3098, 0.2549, 0.2843],
        [0.7674, 0.9477, 0.8390],
        [0.2776, 0.3942, 0.9080],
        [0.6597, 0.8117, 0.593

In [213]:
n = inputs.size(0)
num_dim = inputs.size(1)
targets_ = list(set(targets.data))
num_class = len(targets_)

targets_ = Variable(torch.LongTensor(targets_))
mask_ = targets.repeat(num_class, 1).eq(targets_.int().repeat(n, 1).t())
centers = []
inputs_list = []

# calculate the centers for every class in one mini-batch
for i, target in enumerate(targets_):
    mask_i = mask_[i].repeat(num_dim, 1).t()
    input_ = inputs[mask_i].resize(len(inputs[mask_i]) // num_dim, num_dim)
    centers.append(torch.mean(input_, 0))
    inputs_list.append(input_)

centers = [centers[i].resize(1, num_dim) for i in range(len(centers))]
centers = torch.cat(centers, 0)

# compute centers loss here
dist_ap, dist_an = [], []
centers_dist = euclidean_dist(centers)

c:\users\paoso\appdata\local\programs\python\python36\lib\site-packages\torch\tensor.py:263: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [216]:
centers

tensor([[0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.4525, 0.6165],
        [0.4525, 0.6165],
        [0.5161, 0.7041],
        [0.4525, 0.6165],
        [0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.5534, 0.7989],
        [0.4525, 0.6165],
        [0.4525, 0.6165],
        [0.4525, 0.6165],
        [0.4525, 0.6165],
        [0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.5161, 0.7041],
        [0.5534, 0.7989],
        [0.5161, 0.7041],
        [0.5534, 0.7989],
        [0.5534, 0.7989],
        [0.4525, 0.6165],
        [0.5534, 0.7989],
        [0.5534, 0.7989],
        [0.5161, 0.7041],
        [0.4525, 0.6165],
        [0.4525, 0.6165],
        [0.4525, 0.6165],
        [0.5161, 0.7041],
        [0.4525, 0.6165]], grad_fn=<CatBackward>)

In [244]:
num_of_instances_per_appeared_class

tensor([[8.],
        [8.],
        [1.],
        [8.]])

In [250]:
mean_embedding_per_appeared_class.shape[0]

4

In [251]:
inputs

tensor([[0.7317, 1.1191],
        [0.4993, 0.7516],
        [0.3784, 0.4306],
        [0.4247, 0.4944],
        [0.4893, 0.5936],
        [0.3789, 0.5991],
        [0.4292, 0.4229],
        [0.3429, 0.4065],
        [0.6960, 1.0874],
        [0.5234, 0.7607],
        [0.4609, 0.6476],
        [0.7493, 1.0864],
        [0.5097, 0.9073],
        [0.3025, 0.2970],
        [0.4618, 0.6627],
        [0.5334, 0.7266],
        [0.5623, 0.8904],
        [0.4370, 0.5792],
        [0.4826, 0.6175],
        [0.5916, 0.7889],
        [0.6096, 0.7613],
        [0.3808, 0.4279],
        [0.7977, 1.1399],
        [0.2738, 0.4057],
        [0.3934, 0.6440],
        [0.2864, 0.4146],
        [0.8324, 1.1783],
        [0.4294, 0.4811],
        [0.6909, 1.0049],
        [0.5130, 0.7124],
        [0.2720, 0.4012],
        [0.5106, 0.6091]], grad_fn=<MmBackward>)

In [255]:
inputs=torch.from_numpy(np.load('inputs.npy'))
targets=torch.from_numpy(np.load('targets.npy'))

In [257]:
targets

tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
        0, 1, 2, 3, 0, 1, 2, 3], dtype=torch.int32)

In [258]:
inputs=inputs.cpu().float()
targets=targets.cpu().long()
one_hot_targets=torch.zeros(targets.shape[0], targets.max()+1).scatter_(1,torch.unsqueeze(targets,1), 1)#转成one_hot编码
num_of_instances_per_appeared_class=torch.unsqueeze(one_hot_targets.sum(0),1)
# num_of_instances_per_appeared_class[num_of_instances_per_appeared_class==0]=1e-6#避免除零操作

transposedTargets=one_hot_targets.t()
sum_of_embeddings_per_appeared_class=torch.mm(transposedTargets,inputs)
mean_embedding_per_appeared_class=sum_of_embeddings_per_appeared_class/(num_of_instances_per_appeared_class+1e-6)

mean_embedding_all=inputs.mean(0)
temp=mean_embedding_per_appeared_class-mean_embedding_all
S_b=torch.mm((temp*num_of_instances_per_appeared_class).t(),temp)

temp2=inputs-mean_embedding_all
S_t=torch.mm(temp2.t(),temp2)

In [276]:
res=torch.zeros(inputs.shape[1],inputs.shape[1])
for i in range(inputs.shape[0]):
    temp=(inputs[i,:]-mean_embedding_all).unsqueeze(0)
    res+=temp.t().mm(temp)
res

tensor([[ 2.4101, -0.5024, -0.3519],
        [-0.5024,  2.4872,  0.0395],
        [-0.3519,  0.0395,  3.1118]])

In [273]:
(mean_embedding_per_appeared_class[i,:]-mean_embedding_all).unsqueeze(0)

tensor([[ 0.0849, -0.1643, -0.1491]])

In [278]:
1.0/torch.trace(torch.mm(S_b,torch.inverse(S_t+1e-6*torch.eye(S_t.shape[0]))))

tensor(2.3739)