In [4]:
import torch
from torch.autograd import Variable

In [6]:
data_size = 32
input_dim = 3
output_dim = 2
num_class = 4
x = Variable(torch.rand(data_size, input_dim), requires_grad=False)
w = Variable(torch.rand(input_dim, output_dim), requires_grad=True)
inputs = x.mm(w)
y_ = 8*list(range(num_class))
targets = Variable(torch.IntTensor(y_))

In [12]:
import numpy as np

In [17]:
inputs=np.random.rand(data_size,input_dim)

In [20]:
targets=np.array(8*list(range(num_class)))

In [24]:
np.save('inputs.npy',inputs)
np.save('targets.npy',targets)

In [33]:
torch.from_numpy(inputs)

tensor([[0.3324, 0.6856, 0.1523],
        [0.7529, 0.7688, 0.6183],
        [0.2742, 0.2200, 0.9693],
        [0.4818, 0.5265, 0.8199],
        [0.9567, 0.6536, 0.7073],
        [0.1343, 0.0573, 0.3201],
        [0.5711, 0.7084, 0.4961],
        [0.1555, 0.7137, 0.9226],
        [0.8204, 0.1300, 0.8127],
        [0.9781, 0.2432, 0.8335],
        [0.5221, 0.4624, 0.9861],
        [0.4376, 0.8552, 0.6484],
        [0.8922, 0.0657, 0.1166],
        [0.7064, 0.5949, 0.1227],
        [0.0469, 0.9482, 0.6797],
        [0.1598, 0.9735, 0.6525],
        [0.3287, 0.8011, 0.2352],
        [0.7624, 0.4998, 0.2242],
        [0.8136, 0.8486, 0.2725],
        [0.2237, 0.8923, 0.6831],
        [0.5758, 0.4865, 0.0819],
        [0.7716, 0.8008, 0.0637],
        [0.4058, 0.8306, 0.7508],
        [0.5420, 0.4746, 0.9838],
        [0.7328, 0.3135, 0.9274],
        [0.6032, 0.6289, 0.3127],
        [0.2992, 0.6876, 0.5736],
        [0.4998, 0.7625, 0.1210],
        [0.0325, 0.0674, 0.0866],
        [0.095

In [57]:
targets=torch.zeros(targets.shape[0], targets.max()+1).scatter_(1,torch.unsqueeze(targets.long(),1), 1)

In [158]:
targets=torch.from_numpy(np.load('targets.npy'))

In [66]:
num_of_instances_per_appeared_class=torch.unsqueeze(targets.sum(0),1)

In [82]:
num_of_instances_per_appeared_class=targets.sum(0)

In [86]:
num_of_instances_per_appeared_class[num_of_instances_per_appeared_class!=0]+=1e-6

tensor([8.0000, 8.0000, 8.0000, 8.0000])

In [99]:
A=torch.rand(3,2)

 A==0

In [111]:
targets

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [113]:
targets=torch.zeros(targets.shape[0], targets.max()+1).scatter_(1,torch.unsqueeze(targets.long(),1), 1)#转成one_hot编码
num_of_instances_per_appeared_class=torch.unsqueeze(targets.sum(0),1)
num_of_instances_per_appeared_class[num_of_instances_per_appeared_class==0]=1e-6#避免除零操作


In [114]:
num_of_instances_per_appeared_class

tensor([[8.],
        [8.],
        [8.],
        [8.]])

In [135]:
transposedTargets=targets.t()

In [138]:
sum_of_embeddings_per_appeared_class=transposedTargets.mm(inputs.float())

In [145]:
mean_embedding_per_appeared_class=sum_of_embeddings_per_appeared_class/num_of_instances_per_appeared_class

In [164]:
square_diff_per_instance=(inputs.float()-torch.index_select(input=mean_embedding_per_appeared_class,dim=0,index=targets.long()))**2

In [167]:
sum_of_square_diff_per_appeared_class=torch.mm(transposedTargets,square_diff_per_instance).sum(1)

In [170]:
sum_of_square_diff_per_appeared_class=torch.unsqueeze(sum_of_square_diff_per_appeared_class,1)

In [174]:
var_of_embeddings_per_appeared_class

tensor([[0.2840],
        [0.2240],
        [0.1490],
        [0.1756]])

In [172]:
var_of_embeddings_per_appeared_class=sum_of_square_diff_per_appeared_class/num_of_instances_per_appeared_class

In [175]:
from torch.nn.functional import pairwise_distance

In [178]:
pairwise_distance(mean_embedding_per_appeared_class,mean_embedding_per_appeared_class,p=2)

tensor([1.7321e-06, 1.7321e-06, 1.7321e-06, 1.7321e-06])

In [179]:
def expanded_pairwise_distances(x, y=None):
    '''
    Input: x is a Nxd matrix
           y is an optional Mxd matirx
    Output: dist is a NxM matrix where dist[i,j] is the square norm between x[i,:] and y[j,:]
            if y is not given then use 'y=x'.
    i.e. dist[i,j] = ||x[i,:]-y[j,:]||^2
    '''
    if y is not None:
         differences = x.unsqueeze(1) - y.unsqueeze(0)
    else:
        differences = x.unsqueeze(1) - x.unsqueeze(0)
    distances = torch.sum(differences * differences, -1)
    return distances

In [183]:
inter_loss_matrix=expanded_pairwise_distances(mean_embedding_per_appeared_class)
intra_loss_matrix=var_of_embeddings_per_appeared_class+var_of_embeddings_per_appeared_class.t()

In [187]:
torch.max(intra_loss_matrix-inter_loss_matrix+1,0)

(tensor([1.5680, 1.4967, 1.3225, 1.3511]), tensor([0, 0, 3, 3]))

In [196]:
loss_matrix=intra_loss_matrix-inter_loss_matrix+1
loss_matrix[loss_matrix<0]=0

In [201]:
loss_matrix=loss_matrix-torch.eye(loss_matrix.shape[0])*loss_matrix

In [202]:
torch.max(loss_matrix)

tensor(1.4967)